name: minesweeper
description: "Minesweeper Game with C++ Backend"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  window_manager: ^0.5.1
  cpp_flutter_ffi: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Audiowide
      fonts:
        - asset: lib/assets/fonts/Audiowide/Audiowide-Regular.ttf
  
  assets:
    - lib/assets/images/background.png

